# Default initial position for each movable joint
# These positions will be used as the starting configuration for planning
initial_positions:
  shoulder_pan_joint: 0.0
  shoulder_lift_joint: 0.0
  elbow_joint: 1.57
  wrist_1_joint: -1.57
  wrist_2_joint: -1.57
  wrist_3_joint: 0.0
